services:
  - type: web
    name: card-game-31-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7

  - type: web
    name: card-game-31-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    rootDir: frontend
    envVars:
      - key: REACT_APP_API_URL
        value: https://card-game-31-backend.onrender.com
